### ISSUE TITLE
DTU dataset coordinate system?

### ISSUE THREAD

**Issue by sagniklp** [sxyu/pixel-nerf#2]
In the loader for dtu dataset there is a coordinate transform step. 
Does it use the Blender coordinate system or OpenCV?

**Comment by sxyu** [comment]
Hi Sagnik,
Good question. We (quite arbitrarily) used a `x right, y up, z out` RH coordinated system for *camera space*. Since DVR uses the OpenCV system `x right, y down, z in`, I adjust the camera pose matrix by a similarity transform flipping y,z axes.
The *world space* is the original DTU coordinate system (up to scaling) from the scanning system, which is right-handed but not really axis-aligned I think.

**Comment by phongnhhn92** [comment]
@sagniklp @sxyu 
Hi guys, I have a quick question.
In the DTU dataloader, after the transformation [step](https://github.com/sxyu/pixel-nerf/blob/ddddb6b8f9dd29972305597c2d8ce31ededa82eb/src/data/DVRDataset.py#L204), the output pose is in camera or world space (cam-to-world or world-to-cam) ?
